#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# We want to remove php images that are not used by any containers.
# We use `podman rmi` to remove images, ignoring errors if they are in use.

for img_id in $(podman images --quiet --filter=reference='ghcr.io/stephdl/lamp-server*:*'); do
    # try to remove the image, ignoring errors if it's in use
    podman rmi "$img_id" 2>/dev/null || true
done
