#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "TRAEFIK_HOST",
        "TRAEFIK_HTTP2HTTPS",
        "MYSQL_USER_NAME",
        "MYSQL_USER_DB",
        "CREATE_MYSQL_USER",
        "PHP_UPLOAD_MAX_FILESIZE",
        "PHPMYADMIN_ENABLED",
        "PHP_VERSION"
    ]:
    agent.set_env(evar, original_environment[evar])
