#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)
renv = request['environment']

configure_retval = agent.tasks.run(agent_id=os.environ['AGENT_ID'], action='configure-module', data={
    "host": renv["TRAEFIK_HOST"],
    "http2https": renv["TRAEFIK_HTTP2HTTPS"] == "True",
    "mysql_user_name": renv["MYSQL_USER_NAME"],
    "mysql_user_db": renv["MYSQL_USER_DB"],
    "create_mysql_user": renv["CREATE_MYSQL_USER"] == "True",
    "mysql_admin_pass": agent.read_envfile("password.env")["MYSQL_ADMIN_PASS"],
    "mysql_user_pass": agent.read_envfile("password.env")["MYSQL_USER_PASS"],
    "php_upload_max_filesize": renv["PHP_UPLOAD_MAX_FILESIZE"].removesuffix('M'),
    "php_memory_limit": renv["PHP_MEMORY_LIMIT"].removesuffix('M'),
    "php_max_execution_time": renv["PHP_MAX_EXECUTION_TIME"],
    "phpmyadmin_enabled": renv["PHPMYADMIN_ENABLED"] == "True",
    "php_version": renv["PHP_VERSION"],
})
agent.assert_exp(configure_retval['exit_code'] == 0, "The configure-module subtask failed!")
